- src: https://github.com.cnpmjs.org/codezm/ansible-role-php.git
  version: 1.0.0
  name: codezm.php

- src: https://github.com.cnpmjs.org/codezm/ansible-role-nginx.git
  version: 1.0.0
  name: codezm.nginx

- src: https://github.com.cnpmjs.org/codezm/ansible-role-mysql.git
  version: master
  name: codezm.mysql

- src: https://github.com.cnpmjs.org/codezm/ansible-role-common.git
  version: master
  name: codezm.common
